base.url=https://www.testerrank.com/banking
username=rahul@netbank.com
password=Bank@123
browser=chrome
timeout=10

api.base.url=https://www.testerrank.com
api.valid.email=testuser@testerrank.com
api.valid.password=Test@123