name: Automation Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run automation tests
        run: mvn clean test

      - name: Generate Allure report
        if: always()
        run: mvn io.qameta.allure:allure-maven:report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          retention-days: 30